### PR TITLE
Fix: Add CSV export for quest users

### LINKED ISSUE #388: New route: get_quest_users_csv
## Description 📹

Create a new route at `src/endpoints/admin/quest/get_quest_users_csv.rs` that serves the same data as the existing `get_quest_users.rs` but in CSV format instead of JSON. This route will help administrators easily export user participation data in quests.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:
   Fork the repository and create a new branch using the issue number:

```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:

* [ ] Create a new file `src/endpoints/admin/quest/get_quest_users_csv.rs`.
* [ ] Import the same dependencies as in `get_quest_users.rs` and add CSV handling (e.g., `csv`, `serde`).
* [ ] Reuse the logic to fetch quest users from the existing module.
* [ ] Convert the result data into CSV format using the `csv` crate.
* [ ] Set the appropriate content type in the response (`text/csv`).
* [ ] Add error handling to return appropriate HTTP responses in case of failure.

3. **Run Tests and Commit Changes**:
   Make sure your changes don't break existing functionality and commit with a clear message:

```bash
   git commit -m "Fix: Add CSV export for quest users"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

* **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
* **Timeframe**: Complete the task within **3 business days**.
* **Closing the Issue**: In your PR description, close the issue by writing Close #\[issue\_id].
* **Review Process**:

  * Once you've submitted your PR, change the label to **"ready for review"**.
  * If changes are requested, address them and then update the label back to **"ready for review"** once done.
* **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by SkyWarrior123**
**Description**  
This PR introduces a new admin endpoint: `/admin/quests/get_quest_users_csv`, which enables exporting a list of user addresses who have completed tasks for a specific quest in CSV format.

This is particularly useful for admins who want to analyze user participation or import data into external tools.

---

**Changes**  
- Added a new route `get_quest_users_csv` under `admin/quest`.  
- Queries `tasks` and `completed_tasks` collections to identify eligible users.  
- Applies quest-level authorization using `verify_quest_auth`.  
- Converts unique user addresses to hex format and returns them as a downloadable CSV.  
- Added `csv = "1.3.1"` to dependencies in `Cargo.toml`.  
- Registered the new module in `mod.rs`.

---

**Testing**  
- Verified the endpoint locally.  
- Tested CSV output for `quest_id`.  
- Checked authorization logic to ensure only quest owners can fetch the data.

---

**Issue**  
Close #388

---

**Notes**  
Ready for review. ✅

### CODE REVIEW

**Comment by SkyWarrior123** [comment]
Hey @Marchand-Nicolas, 
    Could you look into the above PR that I contributed for the get_quest_users_csv

File: src/endpoints/admin/quest/get_quest_users_csv.rs [hunk 1]
```diff
@@ -0,0 +1,172 @@
+// src/endpoints/admin/quest/get_quest_users_csv.rs
```
Comment (Marchand-Nicolas) [inline src/endpoints/admin/quest/get_quest_users_csv.rs]: Remove this comment

File: src/endpoints/admin/quest/get_quest_users_csv.rs [hunk 2]
```diff
@@ -0,0 +1,172 @@
...
+use crate::middleware::auth::auth_middleware;
+use crate::models::{AppState, CompletedTaskDocument, QuestDocument, QuestTaskDocument};
+use crate::utils::{get_error, to_hex, verify_quest_auth}; 
+use axum::{
+    extract::{Extension, Query, State},
+    http::{header, HeaderMap, HeaderValue, StatusCode},
+    response::IntoResponse,
+};
+use axum_auto_routes::route;
+use csv::WriterBuilder; // import from csv crate
```
Comment (Marchand-Nicolas) [inline src/endpoints/admin/quest/get_quest_users_csv.rs]: Remove this comment

**Review by Marchand-Nicolas — APPROVED** [review]
Perfect lgtm!
