### PR TITLE
Fix: Include quest completion timestamp in get_quest_participants response

### LINKED ISSUE #358: Update get_quest_participants to return the timestamp of quest completion
## Description 📹

**Update `src/endpoints/admin/quest/get_quest_participants.rs` to return the timestamp of quest completion. The timestamp is the greatest `timestamp` among all `completed_task` documents for the specified quest & address.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   - Modify the `get_quest_participants_handler` function to include logic for fetching the greatest timestamp for each participant.
   - Update the aggregation pipeline in the handler to:
     - Fetch the maximum `timestamp` for each participant who has completed all tasks in the quest.
   - Update the response to include the timestamp alongside the participant details.
   - Add necessary error handling for timestamp extraction.

   **TODO List**:
   - [ ] Add `$max` stage in the aggregation pipeline to compute the maximum timestamp.
   - [ ] Include the computed timestamp in the response JSON.
   - [ ] Test the function to ensure it works with mock `completed_task` data.
   - [ ] Document the changes in the function comments.

   **Example Code Snippet for Aggregation Update**:
   ```rust
   let pipeline = vec![
       doc! { "$match": { "task_id": { "$in": &task_ids } } },
       doc! { "$group": {
           "_id": "$address",
           "task_ids": { "$addToSet": "$task_id" },
           "max_timestamp": { "$max": "$timestamp.$numberLong" }
       }},
       doc! { "$project": {
           "address": "$_id",
           "tasks_completed_count": { "$size": "$task_ids" },
           "quest_completion_timestamp": "$max_timestamp"
       }},
   ];
   ```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
   ```bash
   git commit -m "Fix: Include quest completion timestamp in get_quest_participants response"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by TropicalDog17**
Close #358

### CODE REVIEW

**Comment by Marchand-Nicolas** [comment]
Hello @TropicalDog17 when will the PR be ready for review ?

**Comment by TropicalDog17** [comment]
Hey please review this PR. Thank you so much! @Marchand-Nicolas

File: src/config.rs [hunk 1]
```diff
@@ -229,8 +229,10 @@ pub fn load() -> Config {
     let args: Vec<String> = env::args().collect();
     let config_path = if args.len() <= 1 {
         "config.toml"
-    } else {
+    } else if (args.len() > 1) && (args.get(1).unwrap().contains("toml")) {
```
Comment (Marchand-Nicolas) [inline src/config.rs]: Why ?

File: src/tests/endpoints.rs [hunk 2]
```diff
@@ -26,4 +26,8 @@ pub mod tests {
         let response = client.get(endpoint).send().await.unwrap();
         assert_eq!(response.status(), StatusCode::OK);
     }
+
+    // #[tokio::test]
+    // pub async fn test_get_quest_participants() {
```
Comment (Marchand-Nicolas) [inline src/tests/endpoints.rs]: You can remove this

File: src/endpoints/get_quest_participants.rs [hunk 3]
```diff
@@ -106,5 +125,167 @@ pub async fn handler(
         }
     }
 
-    return (StatusCode::OK, Json(res)).into_response();
+    (StatusCode::OK, Json(res)).into_response()
+}
+#[cfg(test)]
```
Comment (Marchand-Nicolas) [inline src/endpoints/get_quest_participants.rs]: No need to have the tests, but it was a good idea to make sure everything was working. The problem is that if we run tests in production, it'll reset the db

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
As said in the issue, the route we want to update is src/endpoints/admin/quest/get_quest_participants.rs, not src/endpoints/get_quest_participants.rs,

**Comment by Marchand-Nicolas** [comment]
Hello @TropicalDog17 everything good ?

**Comment by TropicalDog17** [comment]
Hi sorry for the delay, can you review @Marchand-Nicolas

File: src/config.rs [hunk 4]
```diff
@@ -229,8 +229,10 @@ pub fn load() -> Config {
...
         args.get(1).unwrap()
+    } else {
```
Comment (Marchand-Nicolas) [inline src/config.rs]: No need to have these changes, you can revert

File: src/tests/endpoints.rs [hunk 5]
```diff
@@ -26,4 +26,8 @@ pub mod tests {
         let response = client.get(endpoint).send().await.unwrap();
         assert_eq!(response.status(), StatusCode::OK);
     }
+
+    // #[tokio::test]
```
Comment (Marchand-Nicolas) [inline src/tests/endpoints.rs]: No need to have these comments

File: src/endpoints/admin/quest/get_quest_participants.rs [hunk 6]
```diff
@@ -99,3 +101,168 @@ pub async fn get_quest_participants_handler(
     let participants_json = json!({ "participants": participants });
     (StatusCode::OK, Json(participants_json)).into_response()
 }
+
+// #[cfg(test)]
```
Comment (Marchand-Nicolas) [inline src/endpoints/admin/quest/get_quest_participants.rs]: No need to have these comments

File: src/endpoints/admin/quest/get_quest_participants.rs [hunk 7]
```diff
@@ -58,11 +58,13 @@ pub async fn get_quest_participants_handler(
         doc! { "$match": { "task_id": { "$in": &task_ids } } },
         doc! { "$group": {
             "_id": "$address",
-            "task_ids": { "$addToSet": "$task_id" }
+            "task_ids": { "$addToSet": "$task_id" },
+            "max_timestamp": { "$max": "$timestamp.$numberLong" }
```
Comment (Marchand-Nicolas) [inline src/endpoints/admin/quest/get_quest_participants.rs]: Error aggregating completed tasks: Kind: Command failed: Error code 16410 (Location16410): FieldPath field names may not start with '$'. Consider using $getField or $setField., labels: {}

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

**Comment by Marchand-Nicolas** [comment]
Hello @TropicalDog17 everything good ?

**Comment by TropicalDog17** [comment]
Hi @Marchand-Nicolas I struggle to debug this, since I am not quite able to setup the enviroment properly, can you help me? Sorry for any inconvenience

**Comment by Marchand-Nicolas** [comment]
Hello @TropicalDog17 here is a guide to help you setup the project: https://github.com/lfglabs-dev/api.starknet.quest/blob/testnet/README.md
You need to update this file: src/endpoints/admin/quest/get_quest_participants.rs
An example pipeline has been provided in the issue. You might just need to copy paste it

**Comment by Marchand-Nicolas** [comment]
Hello @TropicalDog17 Can I assign someone else ? It's been more than a month

**Comment by TropicalDog17** [comment]
> Hello @TropicalDog17 here is a guide to help you setup the project: https://github.com/lfglabs-dev/api.starknet.quest/blob/testnet/README.md You need to update this file: src/endpoints/admin/quest/get_quest_participants.rs An example pipeline has been provided in the issue. You might just need to copy paste it

The pipeline not work i think

**Comment by TropicalDog17** [comment]
@Marchand-Nicolas could you help me test the pipeline, I am able to set up the project and authen the admin route, create new quest. But I am not able to populate some tasks for testing. I think it will be a good idea to has some scripts for populate some mock data for testing.
 And it seems the project has low test coverage, I tried to write some tests but it is very difficult the way the project is written.

**Comment by Marchand-Nicolas** [comment]
> @Marchand-Nicolas could you help me test the pipeline, I am able to set up the project and authen the admin route, create new quest. But I am not able to populate some tasks for testing. I think it will be a good idea to has some scripts for populate some mock data for testing. And it seems the project has low test coverage, I tried to write some tests but it is very difficult the way the project is written.

You can run the frontend to add tasks https://github.com/lfglabs-dev/starknet.quest/

**Comment by Marchand-Nicolas** [comment]
You can test your pipeline in Compass

**Review by Marchand-Nicolas — APPROVED** [review]
lgtm
